### PR TITLE
Add LINK and UNLINK methods

### PR DESCRIPTION
**Pull request by justim**
- Add two new non-data methods: LINK and UNLINK
- See https://tools.ietf.org/html/draft-snell-link-method-12

### CODE REVIEW

**Comment by skellock** [comment]
Wow.  I had no idea this was a thing.  Thank you.

**Comment by justim** [comment]
My pleasure :)

**Comment by justim** [comment]
Thanks.

**Comment by skellock** [comment]
Shipped in `0.6.0`.  Thanks again.

**Pull request merged**
