### PR TITLE
:hammer: Switch to fast async

### PR DESCRIPTION
**Pull request by cloud-walker**
~Not tested on a real application ⚠️~
Tested on my application and fixes **chrome 34** 🎉

### CODE REVIEW

**Comment by cloud-walker** [comment]
We need to "revert" this? https://github.com/skellock/apisauce/commit/386f84e33017fd7f89623041d1ea53e691a065dc

I've already fired the babel-runtime things, you sure we need to remove p-waterfall and ramdasauce?

**Comment by cloud-walker** [comment]
I've removed babel-preset-stage-0 to avoid including the runtime-transform.
I've added the support for object-spread-operator only

Two questions:
- Should I move the two new dependencies on `devDependencies`?
- on node `7.6` async/await is supported natively, we can virtually remove the `fast-async` dependency from the `.babelrc` if you want

**Comment by skellock** [comment]
It's not so much a big deal to have sloppy devDependencies.  But the dependencies should be more lean.

We're not doing multiple builds, for different environments, so we need to support older nodes.

**Comment by cloud-walker** [comment]
The PR has no conflicts, I did not understand your review, what we need to do?

**Comment by cloud-walker** [comment]
Tested on my application!

**Pull request merged**
